---
- name: sync bitwarden vault
  ansible.builtin.command:
    cmd: bw sync
  delegate_to: localhost
  become: false
  run_once: true
  changed_when: false

- name: get bitwarden status
  ansible.builtin.command:
    cmd: bw status
  register: bw_status
  delegate_to: localhost
  become: false
  run_once: true
  changed_when: false

- name: assert bitwarden vault is unlocked
  ansible.builtin.assert:
    that:
      - bw_status.stdout|from_json |json_query('status') == "unlocked"
    fail_msg: "Bitwarden vault is locked. Please unlock and run playbook again."
    success_msg: "Bitwarden vault is unlocked, continuing..."